spring.application.name=market

# SQLite Database connection
spring.datasource.url=jdbc:sqlite:project_db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate Dialect setup
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
